language: node_js

node_js:
- "stable"

env:
  global:
    - CXX=g++-4.8
    - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/test/encrypted/client-secret.json
    - GCLOUD_PROJECT=mxfactorial

before_install:
- if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
    mkdir -p $HOME/gcloud &&
    wget https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
    cd $HOME/gcloud &&
    tar xzf google-cloud-sdk.tar.gz &&
    printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
    source $HOME/.bashrc &&
    cd $TRAVIS_BUILD_DIR;
  fi
- openssl aes-256-cbc -K $encrypted_5979ecf7a4d6_key -iv $encrypted_5979ecf7a4d6_iv -in test/encrypted/client-secret.json.enc -out test/encrypted/client-secret.json -d
- if [ -a test/encrypted/client-secret.json ]; then
    gcloud auth activate-service-account --key-file test/encrypted/client-secret.json;
  fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  directories:
  - node_modules

script: "npm run-script test-travis"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"